config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }


  get '/dutables/project_list_by_manager' , controller: "dutables", action: "project_list_by_manager"
  get 'feedbacks/get_feedback'

  resources :dutables , :projects ,:feedbacks



  resources :schedulers do
    resources :feedbacks
  end

  resources :requirements do
    resources :candidates do
      resources :schedulers
    end
  end

  get 'users/index'
  get 'admin/index'
  get 'candidates/allcandidate'

  get "requirements/candidates/get_candidate_list", controller: "requirements", action: "get_candidate_list"
  get "dutables/projects/get_project_list", controller: "dutables", action: "get_project_list"
  get "dutable/get_project_requirement_details/:id" , controller: "dutables", action: "get_project_requirement_details", as: "dutable_get_project_requirement_details"



end

app/models/scheduler.rb
class Scheduler < ApplicationRecord
  resourcify
  belongs_to :candidate
  belongs_to :requirement
  has_many :feedbacks
  belongs_to :user
  validate :interview_date_is_equal_or_greater_than_today




  private

  def interview_date_is_equal_or_greater_than_today
    return if interview_date.blank?
    if interview_date < (Date.today)
      errors.add(:interview_date, "cannot be a date before today")
    end
  end



end

app/controllers/schedulers_controller.rb
class SchedulersController < ApplicationController


  def index
    @schedulers = Scheduler.includes(:feedbacks).all
    @employee_feedback = Scheduler.where(user_id: current_user.id)
    @projects = Project.where(user_id: current_user.id)
    @a = @projects.pluck(:id)
    @b = Requirement.where("project_id IN (?)", @a)
    @c = @b.pluck(:id)
    @d =Scheduler.where("requirement_id IN (?)", @c)
  end

  def new
    @requirement = Requirement.find(params[:requirement_id])
    @candidate = Candidate.find(params[:candidate_id])
    @scheduler = @candidate.schedulers.build
    @users = User.all
  end


  def show
    @scheduler= Scheduler.find(params[:id])
  end

  def create
    @requirement = Requirement.find(params[:requirement_id])
    @candidate = Candidate.find(params[:candidate_id])
    @scheduler =  @candidate.schedulers.new(schedulers_params)
    @scheduler.requirement_id = params[:requirement_id]

      respond_to do |format|
        @scheduler.save
        InterviewInfoMailer.candidate_information(@scheduler).deliver
        format.html {render 'show', notice: 'Interview schedule' }
      end

  end

  def update
    respond_to do |format|
      if @scheduler.update(schedulers_params)
        format.html { redirect_to @scheduler , notice: 'Interview was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduler }
      else
        format.html { render :edit }
        format.json { render json: @scheduler.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  def schedulers_params
    params.require(:scheduler).permit(:start_time, :end_time, :interview_date, :candidate_id, :user_id, :requirement_id)
  end


end

app/helpers/schedulers_helper.rb
module SchedulersHelper
end

app/views/schedulers/_employee_feedback_page.html.erb
<h1>Listing Interviews</h1>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Candidate name</th>
      <th>Interviewer</th>
      <th>Interview Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Round</th>
      <th>Type</th>
      <th>Last Feedback</th>
      <th>Form</th>
      <th>Feedback Details</th>


    </tr>
  </thead>
  <tbody>
    <%@employee_feedback.each do |scheduler| %>
      <tr>
        <td>
          <%= scheduler.candidate.candidate_full_name rescue '' %>
        </td>

        <td>
        <%=scheduler.user.name%>
        </td>

        <td>
          <%= scheduler.interview_date %>
        </td>
        <td>
          <%= scheduler.start_time %>
        </td>
        <td>
          <%= scheduler.end_time %>
        </td>
        <td>
          <%=scheduler.feedbacks.last.stage_name rescue ''%>
        </td>
        <td>
          <%=scheduler.feedbacks.last.round_type rescue ''%>
        </td>
        <td>
          <%on = scheduler.feedbacks.last.status rescue ''  %>
          <%if on == 'Rejected'%>
            <span class="label label-danger arrowed-in">Rejected</span>
          <%elsif on == 'Shortlisted'%>
            <span class="label label-success arrowed">Shortlisted</span>
          <%elsif on == 'Hold'%>
            <span class="label label-warning">Hold</span>
          <%end%>
        </td>
        <td>
        <%= link_to "Feedback Form", new_scheduler_feedback_path(scheduler) %>
        </td>

        <td>

        <%= link_to "Details",  feedbacks_get_feedback_path(:candidate_id => scheduler.candidate.id) %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/schedulers/_feedback.html.erb
<h1>Listing Interviews</h1>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Candidate name</th>
      <th>Interviewer</th>
      <th>Interview Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Round</th>
      <th>Type</th>
      <th>Last Feedback</th>
      <th>Feedback Details</th>
      <th></th>


    </tr>
  </thead>
  <tbody>
    <%  @schedulers.each do |scheduler| %>
      <tr>
        <td>
          <%= scheduler.candidate.candidate_full_name rescue '' %>
        </td>

        <td>
          <%= scheduler.user.name %>
        </td>

        <td>
          <%= scheduler.interview_date %>
        </td>
        <td>
          <%= scheduler.start_time %>
        </td>
        <td>
          <%= scheduler.end_time %>
        </td>
        <td>
          <%=scheduler.feedbacks.last.stage_name rescue ''%>
        </td>
        <td>
          <%=scheduler.feedbacks.last.round_type rescue ''%>
        </td>
        <td>
          <%on = scheduler.feedbacks.last.status rescue ''  %>
          <%if on == 'Rejected'%>
            <span class="label label-danger arrowed-in">Rejected</span>
          <%elsif on == 'Shortlisted'%>
            <span class="label label-success arrowed">Shortlisted</span>
          <%elsif on == 'Hold'%>
            <span class="label label-warning">Hold</span>
          <%end%>
        </td>
        <td>
        <%= link_to "Feedback Form", new_scheduler_feedback_path(scheduler) %>
        </td>

        <td>

        <%= link_to "Details",  feedbacks_get_feedback_path(:candidate_id => scheduler.candidate.id) %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/schedulers/_manager_feedback_page.html.erb
<h1>List of Candidates</h1>
  <%if @d.blank?%>
<h2>No Records Found</h2>

<%else%>


<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Project Name</th>
      <th>Position</th>
      <th>Candidate name</th>
      <th>Interviewer</th>
      <th>Interview Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Round</th>
      <th>Type</th>
      <th>Last Feedback</th>
      <th>Feedback Details</th>


    </tr>
  </thead>
  <tbody>


    <%  @d.each do |scheduler| %>
      <tr>
        <td>
          <%= scheduler.requirement.project.project_name %>
        </td>
        <td>
          <%= scheduler.requirement.position %>
        </td>
        <td>
          <%= scheduler.candidate.candidate_full_name rescue '' %>
        </td>

        <td>
        <%=scheduler.user.name%>
        </td>

        <td>
          <%= scheduler.interview_date %>
        </td>
        <td>
          <%= scheduler.start_time %>
        </td>

        <td>
          <%= scheduler.end_time %>
        </td>
        <td>
          <%=scheduler.feedbacks.last.stage_name rescue ''%>
        </td>
        <td>
          <%=scheduler.feedbacks.last.round_type rescue ''%>
        </td>
        <td>
          <%on = scheduler.feedbacks.last.status rescue ''  %>
          <%if on == 'Rejected'%>
            <span class="label label-danger arrowed-in">Rejected</span>
          <%elsif on == 'Shortlisted'%>
            <span class="label label-success arrowed">Shortlisted</span>
          <%elsif on == 'Hold'%>
            <span class="label label-warning">Hold</span>
          <%end%>
        </td>

        <td>

        <%= link_to "Details",  feedbacks_get_feedback_path(:candidate_id => scheduler.candidate.id) %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<%end%>

app/views/schedulers/edit.html.erb
<h1>Schedule Interview</h1>
<div id="error_explanation">
  <h3>
  <%- if @scheduler.errors.present?%>
    <ul>
      <% @scheduler.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  <%- end%>
</h3>
</div>
<div class ="main-content-inner">
  <div class ="page-content">
    <div class="row">
      <div class="col-xs-8">


            <%= form_for @scheduler, {url: "/requirements/#{params[:requirement_id]}/candidates/#{params[:candidate_id]}/schedulers/#{params[:scheduler_id]}/edit"} do |f| %>

              <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> Interview Date: </label>
                  <div class="col-sm-9">
                    <input type="date" name="scheduler[interview_date]" id="scheduler_interview_date">
                  </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Start Time: </label>
                  <div class="col-sm-9">
                    <input type="time" name="scheduler[start_time]" id="scheduler_start_time" >
                  </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> End Time:</label>
                  <div class="col-sm-9">
                  <input type="time" name="scheduler[end_time]" id="scheduler_end_time" >
                  </div>
              </div>


            


                    <div class="form-group">
                    <label class="col-sm-3 control-label no-padding-right" for="form-field-1">Inteviewer</label>
                      <div class="col-sm-9">
                    <%= f.select :employee_id, Employee.get_employees_from_requirements(@requirement).collect{ |e| [e.full_name, e.id]} %>
                  </div>
                  </div>





                  <div class="form-group">
                    <%= f.submit 'Save' %>
                  </div>
            <% end %>

      </div>
    </div>
  </div>
</div>

app/views/schedulers/index.html.erb
<%if current_user.manager?%>
  <%= render 'manager_feedback_page'%>
<%elsif current_user.team_member?%>
    <%= render 'employee_feedback_page'%>
<%elsif current_user.hr?%>
    <%= render 'feedback'%>
    <%else%>
    <h1>Hello</h1>
<%end%>

app/views/schedulers/new.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<style>
.widget-box {
  padding: 30px;
  padding-left: 0px;
  padding-right: 0px;
  box-shadow: none;
  margin: 3px 0;

  border-radius: 5px;
  border-color: 1px solid #ddd;
  background-color: #f2f2f2;

}
.right{
  float: right;

}
.actions{padding-right: 190px;
  padding-bottom: 10px;}

  </style>

  <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  </div>
  <% end %>
  <% end %>

<center><h1>Schedule Interview</h1></center>
<br>
<div class ="col-md-6 col-md-offset-3 form-horizontal">
  <div class = "widget-box">


    <%= form_for @scheduler, {url: "/requirements/#{params[:requirement_id]}/candidates/#{params[:candidate_id]}/schedulers"} do |f| %>
    <div id="error_explanation">
      <h3>
        <%- if @scheduler.errors.present?%>
        <ul>
          <% @scheduler.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
          <%- end%>
        </h3>
      </div>

      <div class="form-group">
        <label class="col-sm-3 control-label" for="form-field-1"> Interview Date </label>

        <input type="date" class="col-xs col-sm-6"  name="scheduler[interview_date]" id="scheduler_interview_date" required>

      </div>



      <label class="col-sm-3 control-label" for="form-field-1"> Start Time </label>

      <div class="container">
        <div class="row">
          <div class='col-sm-6'>
            <div class="form-group">
              <div class='input-group date' id='datetimepicker4'>
                <input type='text'   name="scheduler[start_time]"  class="form-control" style= "width:380px" required>
                <span class="input-group-addon" style = "width: 0%">
                  <span class="glyphicon glyphicon-time"></span>
                </span>
              </div>
            </div>
          </div>
          <script type="text/javascript">
          $(function () {
            $('#datetimepicker4').datetimepicker({
              format: 'LT'
            });
          });
          </script>
        </div>
      </div>

      <label class="col-sm-3 control-label" for="form-field-1"> End Time </label>
      <div class="container">
        <div class="row">
          <div class='col-sm-6'>
            <div class="form-group">
              <div class='input-group date' id='datetimepicker3'>
                <input type='text'   name="scheduler[end_time]"  class="form-control" style= "width:380px" required>
                <span class="input-group-addon" style = "width: 0%">
                  <span class="glyphicon glyphicon-time"></span>
                </span>
              </div>
            </div>
          </div>

        </div>
      </div>






      <div class="form-group">
        <label class="col-sm-3 control-label" for="form-field-1">Inteviewer </label>
        <div class="col-xs col-sm-6" required>
          <%= f.select :user_id, options_for_select(User.pluck(:name, :id)), {prompt: "Select"}, class: "chosen-select " %>
        </div>
      </div>

      <div class="actions" >
        <%= f.submit 'Save', class: "btn btn-primary right" %>
      </div>
      <% end %>



    </div>
  </div>











<script>


				if(!ace.vars['touch']) {
					$('.chosen-select').chosen({allow_single_deselect:true});
					//resize the chosen on window resize

					$(window)
					.off('resize.chosen')
					.on('resize.chosen', function() {
						$('.chosen-select').each(function() {
							 var $this = $(this);
							 $this.next().css({'width': $this.parent().width()});
						})
					}).trigger('resize.chosen');
					//resize chosen on sidebar collapse/expand
					$(document).on('settings.ace.chosen', function(e, event_name, event_val) {
						if(event_name != 'sidebar_collapsed') return;
						$('.chosen-select').each(function() {
							 var $this = $(this);
							 $this.next().css({'width': $this.parent().width()});
						})
					});


					$('#chosen-multiple-style .btn').on('click', function(e){
						var target = $(this).find('input[type=radio]');
						var which = parseInt(target.val());
						if(which == 2) $('#form-field-select-4').addClass('tag-input-style');
						 else $('#form-field-select-4').removeClass('tag-input-style');
					});
				}


				//chosen plugin inside a modal will have a zero width because the select element is originally hidden
				//and its width cannot be determined.
				//so we set the width after modal is show
				$('#modal-form').on('shown.bs.modal', function () {
					if(!ace.vars['touch']) {
						$(this).find('.chosen-container').each(function(){
							$(this).find('a:first-child').css('width' , '210px');
							$(this).find('.chosen-drop').css('width' , '210px');
							$(this).find('.chosen-search input').css('width' , '200px');
						});
					}
				})

				//or you can activate the chosen plugin after modal is shown
				//this way select element becomes visible with dimensions and chosen works as expected
				$('#modal-form').on('shown', function () {
					$(this).find('.modal-chosen').chosen();
				})


    $(function () {
      $('#datetimepicker3').datetimepicker({
        format: 'LT'
      });
    });



</script>

app/views/schedulers/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <b>Interviewer Name</b>
  <%= @scheduler.user.name %>
</p>
<p>
  <b>Interview date:</b>
  <%= @scheduler.interview_date%>
<p>
  <b>Interview Start time</b>
  <%= @scheduler.start_time %>
</p>
<p>
  <b>Interview End time</b>
  <%= @scheduler.end_time %>
</p>
<p>