config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }


  get '/dutables/project_list_by_manager' , controller: "dutables", action: "project_list_by_manager"
  get 'feedbacks/get_feedback'

  resources :dutables , :projects ,:feedbacks



  resources :schedulers do
    resources :feedbacks
  end

  resources :requirements do
    resources :candidates do
      resources :schedulers
    end
  end

  get 'users/index'
  get 'admin/index'
  get 'candidates/allcandidate'

  get "requirements/candidates/get_candidate_list", controller: "requirements", action: "get_candidate_list"
  get "dutables/projects/get_project_list", controller: "dutables", action: "get_project_list"
  get "dutable/get_project_requirement_details/:id" , controller: "dutables", action: "get_project_requirement_details", as: "dutable_get_project_requirement_details"



end

app/models/candidate.rb
class Candidate < ApplicationRecord
  resourcify
  belongs_to :requirement
  mount_uploader :resume
  has_many :schedulers, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  validates :resume, :first_name, :last_name, :email,  presence: true


  def candidate_full_name
    self.first_name + " " + self.last_name
  end


end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @requirement = Requirement.find(params[:requirement_id])
    @candidates = @requirement.candidates.includes(:candidate)
  end

  def allcandidate
    @candidate = Candidate.all
    @feedback = Feedback.all
  end

  def show

  end

  def new

    @requirement = Requirement.find(params[:requirement_id])
    @candidate = @requirement.candidates.new
  end

  def edit
  end

  def create

    @requirement = Requirement.find(params[:requirement_id])
    @candidate = @requirement.candidates.new(candidate_params)

    respond_to do |format|
        if @candidate.save
          format.html { redirect_to [@requirement,@candidate], notice: 'Candidate was successfully created.' }
          format.js
          format.json { render :show, status: :created, location: @candidate }
        else
          format.html { render :new }
          format.js
          format.json { render json: @candidate.errors, status: :unprocessable_entity }
        end
    end
  end

  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    def candidate_params
      params.require(:candidate).permit(:first_name, :last_name, :contact, :email, :resume, :requirement_id)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_candidate_list.html.erb
<table id="dynamic-table" class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Sr No</th>
      <th>Candidate Name</th>

      <th>Contact</th>
      <th>Email</th>
      <th>Resume</th>
      <th>Interviewer Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%  candidates.each_with_index do |candidate, i| %>
    <tr>
      <td>
        <%=i + 1 %>
      </td>
      <td>
        <%= candidate.candidate_full_name %>
      </td>

      <td>
        <%= candidate.contact %>
      </td>
      <td>
        <%= candidate.email %>
      </td>

      <td>
        <%= link_to "Download Resume", candidate.resume_url %>
      </td>

      <td>

        <%interviewer_feedback = candidate.schedulers.last.feedbacks.last.status rescue nil%>
          <%if interviewer_feedback.present?%>
            <%if interviewer_feedback == 'Rejected'%>
              <span class="label label-danger arrowed-in">Rejected</span>
            <%elsif interviewer_feedback == 'Shortlisted'%>
              <span class="label label-success arrowed">Shortlisted</span>
            <%elsif interviewer_feedback == 'Hold'%>
              <span class="label label-warning">Hold</span>
            <% end%>
        <%else%>
          <span class="label label-primary arrowed arrowed-right">No Feedback Yet</span>
        <%end%>
      </td>


      <%if candidate.requirement.status == "closed" %>
      <td>
        <%= link_to "Schedule_Interview", "#"%>
      </td>
      <%else%>
      <td>
        <%= link_to "Schedule Interview", new_requirement_candidate_scheduler_path(requirement, candidate) %>
      </td>
      <%end%>


    </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates/_form.html.erb
<style>
.widget-box {
  padding: 30px;
  padding-left: 0px;
  padding-right: 0px;
  box-shadow: none;
  margin: 3px 0;

  border-radius: 5px;
  border-color: 1px solid #ddd;
  background-color: #f2f2f2;
}
.right{
  float: right;

}
.actions{padding-right: 200px;
  padding-bottom: 10px;}
  #candidate_resume{padding-right: 405px;
  }
</style>



<div class ="col-md-6 col-md-offset-3 form-horizontal">
  <div class = "widget-box">
    <%= form_for  [@requirement, @candidate] do |f| %>
    <% if @candidate.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@candidate.errors.count, "error")} prohibited this candidate from being saved:" %>
      </h2>
      <ul>
        <% @candidate.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
    </div>
    <% end %>



    <div class="form-group">
      <label class="col-sm-3 control-label " for="form-field-1">First Name</label>
      <input type="text" id="form-field-1" placeholder="First Name" name="candidate[first_name]" class="col-xs col-sm-6" required>

    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label " for="form-field-1">Last Name</label>
      <input type="text" id="form-field-1" placeholder="Last Name" name="candidate[last_name]" class="col-xs col-sm-6" required>

    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label " for="form-field-1">Phone No</label>
      <input type="tel" id="form-field-1" placeholder="Phone No" name="candidate[contact]" class="col-xs col-sm-6" required>

    </div>

    <div class="form-group">
      <label class="col-sm-3 control-label " for="form-field-1">Email</label>
      <input type="email" name="candidate[email]" placeholder="Email" id="candidate_email" class="col-xs col-sm-6" required>
    </div>


    <div  class="form-group">
      <label class="col-sm-3 control-label " for="form-field-1" style= "padding-top:0px">Candidate Resume</label>

      <%=f.file_field :resume%>
    </div>

    <div class="actions" >
      <%= f.submit 'Save' , class: "btn btn-primary right"%>
    </div>


    <center>
      <% end %>

      <%= link_to 'Back', requirements_path, class: "col-sm-3 control-label" %>

    </div>

  </div>

app/views/candidates/allcandidate.html.erb
<h1>Listing candidates</h1>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Candidate Full_Name</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Resume</th>



    </tr>
  </thead>
  <tbody>
    <%  @candidate.each do |candidate| %>
      <tr>
        <td>
          <%= candidate.candidate_full_name %>
        </td>
        <td>
          <%= candidate.contact %>
        </td>
        <td>
          <%= candidate.email %>
        </td>
        <td id="k"><%= link_to "Download Resume", candidate.resume_url  %></td>





      </tr>
    <% end %>
  </tbody>
</table>
<br/>

app/views/candidates/create.js.erb
<%- if @candidate.errors.any? %>


alert("Some fields are empty")


<%- else%>
<%- end%>
window.location.href = "/requirements/<%=@candidate.requirement.id%>"; 

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>
<%= render 'form' %>
<%= link_to 'Show', @candidate %>

<%= link_to 'Back', requirement_candidates_path %>

app/views/candidates/index.html.erb
<h1>Listing candidates</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Contact</th>
      <th>Email</th>
      <th>Resume</th>
      <th></th>


    </tr>
  </thead>
  <tbody>
    <%  @candidates.each do |candidate| %>
      <tr>
        <td>
          <%= candidate.first_name %>
        </td>
        <td>
          <%= candidate.last_name %>
        </td>
        <td>
          <%= candidate.contact %>
        </td>
        <td>
          <%= candidate.email %>
        </td>

         <td id="k"><%= link_to "Download Resume", candidate.resume_url  %></td>
         <%if candidate.requirement.status == "closed" %>
            <td><%= link_to "Schedule Interview", "#"%></td>
         <%else%>
            <td><%= link_to "Schedule Interview", new_requirement_candidate_scheduler_path(@requirement, candidate) %></td>
        <%end%>

      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Candidate',  new_requirement_candidate_path %>

<script>
  function populate_pdf(file){
        var fileName = file;
        //$("#btnShow").click(function () {
            $("#dialog").dialog({
                modal: true,
                title: fileName,
                width: 540,
                height: 450,
                buttons: {
                    Close: function () {
                        $(this).dialog('close');
                    }
                },
                open: function () {
                    var object = "<object data=\"{FileName}\" type=\"application/pdf\" width=\"500px\" height=\"300px\">";
                    object += "If you are unable to view file, you can download from <a href = \"{FileName}\">here</a>";
                    object += " or download <a target = \"_blank\" href = \"http://get.adobe.com/reader/\">Adobe PDF Reader</a> to view the file.";
                    object += "</object>";
                    object = object.replace(/{FileName}/g, "Files/" + fileName);
                    $("#dialog").html(object);
                }

            });
        }
</script>

app/views/candidates/new.html.erb
<center><h1>New Candidate</h1><center>
  <br>
  
<%= render 'form' %>

app/views/candidates/show.html.erb
<p>
  <b>First name:</b>
  <%= @candidate.first_name %>
</p>
<p>
  <b>Last name:</b>
  <%= @candidate.last_name %>
</p>
<p>
  <b>Contact:</b>
  <%= @candidate.contact %>
</p>
<p>
  <b>Email:</b>
  <%= @candidate.email %>
</p>


<%= link_to 'Edit', edit_requirement_candidate_path(@candidate) %>
|
<%= link_to 'Back', requirement_candidates_path %>