config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }


  get '/dutables/project_list_by_manager' , controller: "dutables", action: "project_list_by_manager"
  get 'feedbacks/get_feedback'

  resources :dutables , :projects ,:feedbacks



  resources :schedulers do
    resources :feedbacks
  end

  resources :requirements do
    resources :candidates do
      resources :schedulers
    end
  end

  get 'users/index'
  get 'admin/index'
  get 'candidates/allcandidate'

  get "requirements/candidates/get_candidate_list", controller: "requirements", action: "get_candidate_list"
  get "dutables/projects/get_project_list", controller: "dutables", action: "get_project_list"
  get "dutable/get_project_requirement_details/:id" , controller: "dutables", action: "get_project_requirement_details", as: "dutable_get_project_requirement_details"



end

app/controllers/dutables_controller.rb
class DutablesController < ApplicationController

  def index
    @dutables = Dutable.includes(:projects).all
  end


  def show
    @dutable = Dutable.find(params[:id])
  end


  def new
    @dutable = Dutable.new
    @project = @dutable.projects.build
  end


  def edit
    @dutable = Dutable.find(params[:id])
  end


  def create

    @dutable = Dutable.new(dutable_params)
    respond_to do |format|
      if @dutable.save

        format.html { redirect_to @dutable,notice: 'Delivery Unit Cell created' }
        format.json { render :show, status: :created, location: @dutable }
      else

        format.html { render :new }
        format.json { render json: @dutable.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    @dutable = Dutable.find(params[:id])
    respond_to do |format|
      if @dutable.update(dutable_params)
        format.html { redirect_to @dutable,notice: 'Updated Successfully' }
      else
        render :edit
      end
    end
  end

  def destroy
    Dutable.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to dutable_url, notice: 'Requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_project_list
    @dutable = Dutable.find(params[:id])
    respond_to do |format|
      format.js
    end
  end


  def get_project_requirement_details
    @project = Project.find(params[:id])
    @requirements =@project.requirements.order(created_at: :desc)
  end

  def project_list_by_manager
    @project_list = Project.where(user_id: current_user.id)
  end


  private

  def dutable_params
    params.require(:dutable).permit(:du_name, :du_description, projects_attributes: [:id, :project_name,:pro_description,:user_id, :_destroy] )
  end
end

app/views/dutables/_fields.html.erb
<style>
.widget-box {
  padding: 30px;
  padding-left: 10px;
  padding-right: 0px;
  box-shadow: none;
  margin: 3px 0;

  border-radius: 5px;
  border-color: 1px solid #ddd;
  background-color: #f2f2f2;

}
.right{
  float: center;

}
.actions{padding-right: 50px;
  padding-bottom: 10px;}
</style>
<div class="container">
  <div class="col-md-2">
  </div>
  <div class ="col-md-8 form-horizontal" >
    <div class = "widget-box">
      <%=form_for @dutable do |f| %>
        <% if !@dutable.persisted? %>

        <br>

          <div class="form-group" style ="margin-left:0px">
            <label class="col-sm-3 control-label "for="form-field-1" style="font-size:16px;" >Delivery Unit Name</label>

            <div class="col-sm-9">
              <input type="text" name="dutable[du_name]" id="dutable_du_name" class="col-xs col-sm-8" required>
            </div>
          </div>
          <div class="form-group" style ="margin-left:0px">
            <label class="col-sm-3 control-label"  for="form-field-1" style="padding-top: 10px;font-size:16px;" >Description</label>

            <div class="col-sm-9" style = "padding-top: 10px">
              <textarea name="dutable[du_description]" id="dutable_du_description" class="col-xs col-sm-8" required></textarea>
            </div>
          </div>
      <%end%>





          <table class = 'table ' style= "width: 700px;">
            <thead style="border: 1px solid #ddd;padding: 8px;" >
              <tr>
                <th style="font-weight: 400;"> Project Name </th>
                <th style="font-weight: 400;" > Description </th>
                <th style="font-weight: 400;">Manager</th>
                <th></th>
              </tr>
            </thead>

            <tbody class ='tasks'>
              <%=f.fields_for :projects do |b|%>
              <%= render 'project_fields', :f =>b %>
              <%end%>

            </tbody>

          </table>

          <center>
            <div class ='actions'>
            <%= link_to_add_association 'Add project', f , :projects , class: "btn btn-success",
            data: {association_insertion_node: '.tasks', association_insertion_method: :append}%>

              <br>
              </br>

                  <%= f.submit "Save", class: "btn btn-primary right" %>
              </div>
              <%end%>
          <center>
      </div>
    </div>
    <div class="col-md-2">
    </div>
</div>

app/views/dutables/_project_fields.html.erb
<tr class = "nested-fields">
<td>

<%=f.text_field :project_name%>
</td>

<td>
<%=f.text_area :pro_description%>
</td>

<td>
    <%= f.select :user_id, options_for_select(User.pluck(:name, :id)), {prompt: "Select Project Manager"}, class: "chosen-select form-contrl "%>
</td>

<td>
<%= link_to_remove_association "Remove", f %>

</td>
</tr>


<script>


				if(!ace.vars['touch']) {
					$('.chosen-select').chosen({allow_single_deselect:true});
					//resize the chosen on window resize

					$(window)
					.off('resize.chosen')
					.on('resize.chosen', function() {
						$('.chosen-select').each(function() {
							 var $this = $(this);
							 $this.next().css({'width': $this.parent().width()});
						})
					}).trigger('resize.chosen');
					//resize chosen on sidebar collapse/expand
					$(document).on('settings.ace.chosen', function(e, event_name, event_val) {
						if(event_name != 'sidebar_collapsed') return;
						$('.chosen-select').each(function() {
							 var $this = $(this);
							 $this.next().css({'width': $this.parent().width()});
						})
					});


					$('#chosen-multiple-style .btn').on('click', function(e){
						var target = $(this).find('input[type=radio]');
						var which = parseInt(target.val());
						if(which == 2) $('#form-field-select-4').addClass('tag-input-style');
						 else $('#form-field-select-4').removeClass('tag-input-style');
					});
				}


				//chosen plugin inside a modal will have a zero width because the select element is originally hidden
				//and its width cannot be determined.
				//so we set the width after modal is show
				$('#modal-form').on('shown.bs.modal', function () {
					if(!ace.vars['touch']) {
						$(this).find('.chosen-container').each(function(){
							$(this).find('a:first-child').css('width' , '210px');
							$(this).find('.chosen-drop').css('width' , '210px');
							$(this).find('.chosen-search input').css('width' , '200px');
						});
					}
				})

				//or you can activate the chosen plugin after modal is shown
				//this way select element becomes visible with dimensions and chosen works as expected
				$('#modal-form').on('shown', function () {
					$(this).find('.modal-chosen').chosen();
				})


    $(function () {
      $('#datetimepicker3').datetimepicker({
        format: 'LT'
      });
    });



</script>

app/views/dutables/_project_list.html.erb
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Sr No.</th>
          <th>Projects </th>
          <th>Total Requirements</th>
          <th>Action</th>



        </tr>
      </thead>
      <tbody>
      <% dutable.projects.each_with_index do |project, i|%>
          <tr>
            <td>
              <%= i + 1%>
            </td>
            <td>
              <%= project.project_name%>
            </td>
            <td>
              <span class="badge badge-warning badge-left" ><%=project.requirements.count%></span>
            </td>
            <td>
            <%= link_to "Details".html_safe, project_path(project), class:'btn btn-info '%>
            </td>
          </tr>


        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Add Project',  edit_dutable_path(dutable), class:'ace-icon fa btn btn-primary bigger-110 icon-only  btn-xm'%>

app/views/dutables/edit.html.erb
<center><h1>Add Project</h1><center>
<%= render 'fields' %>

app/views/dutables/get_project_list.js.erb
$("#DuProject-<%=@dutable.id%>").html("<%= escape_javascript render(partial: 'dutables/project_list', locals: {dutable: @dutable}) %>");

app/views/dutables/get_project_requirement_details.html.erb
<Center><h1>Require Positions List</h1></center>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Sr No.</th>
        <th>position</th>
        <th>Status</th>

        <!-- <th></th> -->

      </tr>
    </thead>
    <tbody>

      <% @requirements.each_with_index do |requirement, i| %>
      <tr>
          <td>
            <%=i + 1 %>
          </td>


          <td>
            <%= requirement.position %>
          </td>

          <td>
            <%on = requirement.status %>
            <%if on == 'open'%>
              <span class="label label-success arrowed">Open</span>
              <%elsif on == 'closed'%>
                <span class="label label-danger arrowed-in">Closed</span>
              <%end%>
          </td>
      </tr>



      <% end %>
    </tbody>
  </table>

app/views/dutables/index.html.erb
  <Center><h1>Delivery Units</h1></center>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Sr No.</th>
        <th>Details</th>
        <th>Delivery Unit Name</th>

        <th>No of Projects</th>
        <th></th>
        <!-- <th></th> -->

      </tr>
    </thead>
    <tbody>
      <% @dutables.each_with_index do |d, i| %>
        <tr>
          <td>
            <%=i + 1 %>
          </td>

          <td class="center">
            <div class="action-buttons">
              <a href="<%= dutables_projects_get_project_list_url(id: d.id)%>" class="green bigger-140 show-details-btn" title="Show Details" data-remote=true >
                <i class="ace-icon fa fa-angle-double-down"></i>
                <span class="sr-only">Details</span>
              </a>
            </div>
          </td>

          <td>
            <%= d.du_name %>

          </td>

          <td>
            <%= d.projects.count %>
          </td>

          <td>
          <%= link_to 'Details', dutable_path(d), class:'btn btn-info'%>
          </td>

        </tr>

        <tr class="detail-row">
          <td colspan="12" id="DuProject-<%=d.id%>">

          </td>
      </tr>

          <!-- <td>
          <%= link_to 'Add Project',  edit_dutable_path(d), class: 'class="ace-icon fa fa-wrench  bigger-110 icon-only btn btn-warning btn-xm"'%>
          </td> -->


      <% end %>
    </tbody>
  </table>

          <script>
            $('.show-details-btn').on('click', function(e) {
            	e.preventDefault();
            	$(this).closest('tr').next().toggleClass('open');
            	$(this).find(ace.vars['.icon']).toggleClass('fa-angle-double-down').toggleClass('fa-angle-double-up');
            });
          </script>

app/views/dutables/new.html.erb
<center><h1>New Delivery Unit</h1><center>
  <br>
  <%=render 'fields'%>

app/views/dutables/project_list_by_manager.html.erb
<Center><h1>Project List</h1></center>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Sr No.</th>
        <th>Details</th>
        <th>Project Name</th>

        <th>No of Requirements</th>
        <th></th>
        <!-- <th></th> -->

      </tr>
    </thead>
    <tbody>

      <% @project_list.each_with_index do |project, i| %>
      <tr>
          <td>
            <%=i + 1 %>
          </td>


          <td>
            <%= project.project_name %>
          </td>

          <td>
            <%=project.requirements.count %>
          </td>


          <td>
            <%= link_to 'Details', dutable_get_project_requirement_details_path(project), class:'btn btn-info'%>
          </td>

      </tr>



      <% end %>
    </tbody>
  </table>

app/views/dutables/show.html.erb
    <h1><%=h @dutable.du_name %></h1>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Sr No.</th>
          <th>Projects</th>
          <th>Total Requirements</th>
          <th>Action</th>



        </tr>
      </thead>
      <tbody>
      <% @dutable.projects.each_with_index do |project, i|%>
          <tr>
            <td>
              <%= i + 1%>
            </td>
            <td>
              <%= project.project_name%>
            </td>
            <td>
              <span class="badge badge-warning badge-left" ><%=project.requirements.count%></span>
            </td>
            <td>
            <%= link_to "Details".html_safe, project_path(project), class:'btn btn-info '%>
            </td>
          </tr>


        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Add Project',  edit_dutable_path, class:'ace-icon fa btn btn-primary bigger-110 icon-only  btn-xm'%>