config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }


  get '/dutables/project_list_by_manager' , controller: "dutables", action: "project_list_by_manager"
  get 'feedbacks/get_feedback'

  resources :dutables , :projects ,:feedbacks



  resources :schedulers do
    resources :feedbacks
  end

  resources :requirements do
    resources :candidates do
      resources :schedulers
    end
  end

  get 'users/index'
  get 'admin/index'
  get 'candidates/allcandidate'

  get "requirements/candidates/get_candidate_list", controller: "requirements", action: "get_candidate_list"
  get "dutables/projects/get_project_list", controller: "dutables", action: "get_project_list"
  get "dutable/get_project_requirement_details/:id" , controller: "dutables", action: "get_project_requirement_details", as: "dutable_get_project_requirement_details"



end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

      user ||= User.new # guest user (not logged in)
      if user.hr?
        can :manage, :all
      elsif user.manager?
        can :read , Feedback
      else user.team_member?
        can :read, Feedback
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  resourcify
  belongs_to :requirement
  mount_uploader :resume
  has_many :schedulers, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  validates :resume, :first_name, :last_name, :email,  presence: true


  def candidate_full_name
    self.first_name + " " + self.last_name
  end


end

app/models/dutable.rb
class Dutable < ApplicationRecord
  resourcify
  has_many :projects, dependent: :destroy
  accepts_nested_attributes_for :projects, reject_if: :all_blank, allow_destroy: true
end

app/models/employee.rb
class Employee < ApplicationRecord
    resourcify
    has_and_belongs_to_many :projects

    has_many :employee_requirement_skills, as: :employee_requirement_skillable

    attr_accessor :skill_id

    before_save :build_emp_skills

    def build_emp_skills
      if new_record?
        self.employee_requirement_skills.build(skill_id: self.skill_id)
      end
    end

    def self.get_employees_from_requirements(requirement)
      skill_ids = requirement.employee_requirement_skills.pluck(:skill_id)
      employee_ids = EmployeeRequirementSkill.where(employee_requirement_skillable_type: "Employee", skill_id: skill_ids).pluck(:employee_requirement_skillable_id)
      employees = Employee.where(id: employee_ids)
    end

    def full_name
      self.emp_firstname + " " + self.emp_lastname
    end
  end

app/models/employees_project.rb
class EmployeesProject < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  resourcify
  belongs_to :scheduler
  # before_save :save_details
  belongs_to :candidate
  private

  # def save_details
  #
  #   self.candidate_id = self.scheduler.candidate_id
  #   self.opportunityID = self.scheduler.requirement.opportunityID
  #   # self.candidate_id = Scheduler.find(self.scheduler_id).candidate.id
  #   # self.opportunityID = Requirement.find(Scheduler.find(self.scheduler_id).requirement_id).opportunityID
  #
  # end
end

app/models/project.rb
class Project < ApplicationRecord
  resourcify
  belongs_to :dutable
  has_many :requirements
  has_and_belongs_to_many :employees
  has_many :requirements, dependent: :destroy
  belongs_to :user
  accepts_nested_attributes_for :requirements, reject_if: :all_blank, allow_destroy: true
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  resourcify
  has_many :candidates, dependent: :destroy
  has_one :scheduler, dependent: :destroy
  has_many :employee_requirement_skills, as: :employee_requirement_skillable
  belongs_to :project
  before_save :build_requirement_skills
  attr_accessor :skill_id
  validates :project_id,  presence: true

  def build_requirement_skills
    if new_record?
      self.employee_requirement_skills.build(skill_id: self.skill_id)
    end
  end

  def self.search(search)

    if search
      where('status LIKE ?',"%#{search}%")
    else
      Requirement.all
    end
  end


end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/scheduler.rb
class Scheduler < ApplicationRecord
  resourcify
  belongs_to :candidate
  belongs_to :requirement
  has_many :feedbacks
  belongs_to :user
  validate :interview_date_is_equal_or_greater_than_today




  private

  def interview_date_is_equal_or_greater_than_today
    return if interview_date.blank?
    if interview_date < (Date.today)
      errors.add(:interview_date, "cannot be a date before today")
    end
  end



end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :employee_requirement_skills
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
  has_many :schedulers
  cattr_accessor :current_role
  # def is_hr?
  #
  #   @user = User.find(params[:id])
  #   @user.designation
  # end

  # def is_employee?
  #   current_user.designation == 'Software Engineer'
  # end



  def hr?
    has_role?(:hr)
  end

  def manager?
    has_role?(:manager)
  end

  def team_member?
    has_role?(:team_member)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to  users_index_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_skills(obj)
    skill_ids = obj.employee_requirement_skills.pluck(:skill_id) rescue []
    skills = Skill.where(id: skill_ids)
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedulers_helper.rb
module SchedulersHelper
end

app/views/admin/index.html.erb
<style>

</style>

<div>
<ul>
    <% Dutable.all.each do |du| %>
      <li><%= du.du_name %></li>
        <ul>
            <% du.projects.each do |pr| %>
              <li><%= pr.project_name %></li>
                <ul>
                    <% pr.employees.each do |emp| %>
                      <li><%= emp.emp_firstname %></li>
                    <%end%>
                </ul>
            <%end%>
        </ul>
    <%end%>
</ul>
</div>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p><strong>This form contains <%= pluralize(object.errors.count, 'error') %>.</strong></p>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class='footer'  style="background-color:#92cd00">
  <div class='footer-inner'>
    <div class='footer-content'>
      <span class='bigger-120'>
        <span class='blue bolder' style="color:#92cd00;">Interview Portal</span>
        Application ©2018
      </span>
         
      <span class='action-buttons'>
        <a href='#'>
          <i class='ace-icon fa fa-twitter-square light-blue bigger-150'></i>
        </a>
        <a href='#'>
          <i class='ace-icon fa fa-facebook-square text-primary bigger-150'></i>
        </a>
        <a href='#'>
          <i class='ace-icon fa fa-rss-square orange bigger-150'></i>
        </a>
      </span>
    </div>
  </div>
</div>
<a class='btn-scroll-up btn btn-sm btn-inverse' href='#' id='btn-scroll-up'>
  <i class='ace-icon fa fa-angle-double-up icon-only bigger-110'></i>
</a>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default ace-save-state" id="navbar">
  <div class="navbar-container ace-save-state" id="navbar-container">
    <button class="navbar-toggle menu-toggler pull-left" data-target="#sidebar" id="menu-toggler" type="button">
      <span class="sr-only">Toggle sidebar</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-header pull-left">
      <a class="navbar-brand" href="<%=users_index_path%>">
        <small>

          <%= image_tag("ig-logo.png")%>
        </small>
      </a>
    </div>

      <% if user_signed_in?%>
    <div class="navbar-buttons navbar-header pull-right" role="navigation">
      <ul class="nav ace-nav">
        <li class="light-blue dropdown-modal">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= image_tag("avatar7.png", class: "nav-user-photo") %>
            <span class="user-info">
              <p><%=current_user.name%></p>

            </span>
            <i class="ace-icon fa fa-caret-down"></i>
          </a>
          <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
            <li>
              <a href="#">
                <i class="ace-icon fa fa-cog"></i>
                Settings
              </a>
            </li>
            <li>
              <a href="profile.html">
                <i class="ace-icon fa fa-user"></i>
                Profile
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a rel="nofollow" href="/users/sign_out">
                <i class="ace-icon fa fa-power-off"></i>
                Logout
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <%end%>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_side_bar.html.erb
<div class="sidebar responsive ace-save-state" id="sidebar">
  <ul class="nav nav-list">

    <%if current_user.team_member?%>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="ace-icon fa fa-pencil-square-o"></i>
        <!-- <i class="ace-icon fa fa-users"></i> -->
        Feedback

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">

        <li class="">
          <a href="<%=schedulers_path%>">
            <i class="ace-icon glyphicon glyphicon-list"></i>
            Listing Interviews
          </a>

          <b class="arrow"></b>
        </li>

      </ul>
    </li>
<%elsif current_user.manager?%>


    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="ace-icon fa fa-pencil-square-o"></i>
        <!-- <i class="ace-icon fa fa-users"></i> -->
        Feedback

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">

        <li class="">
          <a href="<%=schedulers_path%>">
            <i class="ace-icon glyphicon glyphicon-list"></i>
            Listing Interviews
          </a>

          <b class="arrow"></b>
        </li>

      </ul>
    </li>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="ace-icon fa fa-pencil-square-o"></i>
        <!-- <i class="ace-icon fa fa-users"></i> -->
        Projects

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">

        <li class="">
          <a href="<%=dutables_project_list_by_manager_path%>">
            <i class="ace-icon glyphicon glyphicon-list"></i>
            Listing Project
          </a>

          <b class="arrow"></b>
        </li>

      </ul>
    </li>

<%elsif current_user.hr?%>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="ace-icon glyphicon glyphicon-asterisk"></i>
        Requirements

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">

        <li class="">
          <a href="<%=requirements_path %>">
            <i class="ace-icon glyphicon glyphicon-list"></i>
            Requirement List
          </a>

          <b class="arrow"></b>
        </li>



      </ul>
    </li>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="menu-icon fa fa-caret-right"></i>
        Delivery Unit Cells

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">
        <li class="">
          <a href="<%=dutables_path %>">
            <i class="ace-icon glyphicon glyphicon-list"></i>
            List of Units
          </a>

          <b class="arrow"></b>
        </li>

        <li class="">
          <a href="<%=new_dutable_path %>">
            <i class="ace-icon glyphicon glyphicon-plus"></i>
            Add Units
          </a>

          <b class="arrow"></b>
        </li>

      </ul>
    </li>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="ace-icon fa fa-pencil-square-o"></i>
        <!-- <i class="ace-icon fa fa-users"></i> -->
        Candidate

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">

        <li class="">
          <a href="<%=candidates_allcandidate_path%>">
            <i class="ace-icon glyphicon glyphicon-list"></i>
            Listing Candidate
          </a>

          <b class="arrow"></b>
        </li>

      </ul>
    </li>


    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="ace-icon fa fa-pencil-square-o"></i>
        <!-- <i class="ace-icon fa fa-users"></i> -->
        Feedback

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">

        <li class="">
          <a href="<%=schedulers_path%>">
            <i class="ace-icon glyphicon glyphicon-list"></i>
            Listing Interviews
          </a>

          <b class="arrow"></b>
        </li>

      </ul>
    </li>

    <%end%>




  </ul>
  <!-- /.nav-list
-->
<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
  <i class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right" id="sidebar-toggle-icon"></i>
</div>
</div>

app/views/layouts/application.html.erb
<html>
<head>
  <link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <title>InterviewPortal</title>
      <%= csrf_meta_tags %>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
        <link href="alert/css/alert.css" rel="stylesheet" />
        <link href="alert/themes/default/theme.css" rel="stylesheet" />
        <script src="alert/js/alert.js"></script>
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
  <body class="no-skin <%= !user_signed_in? ? " login-layout" : ''%>">
    <%= render "layouts/header" %>
      <main role="main">
        <%= render 'layouts/messages' %>
      </main>

    <div class="main-container ace-save-state" id="main-container">
      <% if user_signed_in? %>
      <%= render "layouts/side_bar" %>
          <div class="main-content">
            <div class="main-content-inner">
              <div class="page-content">
                    <div class="breadcrumbs ace-save-state" id="breadcrumbs">
                        <ul class="breadcrumb">
                          <li>
                            <i class="ace-icon fa fa-home home-icon"></i>
                            <a href="<%=users_index_path%>">Home</a>
                          </li>


                        </ul><!-- /.breadcrumb -->
                      </div>
                <%= yield %>
              </div>
            </div>
          </div>
          <% else %>
        <div class="main-content">
          <%= yield %>
        </div>
          <% end %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</head>
</html>